export default {
  id: 'burger',
  name: 'Burger Joint',
  description: 'Hamburguesas artesanales, papas y malteadas',
  icon: 'burger',

  categories: [
    { name: 'Burgers', sort_order: 1 },
    { name: 'Sides', sort_order: 2 },
    { name: 'Drinks', sort_order: 3 },
    { name: 'Shakes', sort_order: 4 },
    { name: 'Kids', sort_order: 5 },
  ],

  items: [
    // Burgers
    { name: 'Clásica', category: 'Burgers', price: 95, description: 'Carne de res 150g, lechuga, tomate, cebolla y salsa especial', prep_time_minutes: 10 },
    { name: 'Cheese Burger', category: 'Burgers', price: 105, description: 'Carne de res 150g con queso cheddar derretido', prep_time_minutes: 10 },
    { name: 'Bacon Burger', category: 'Burgers', price: 120, description: 'Carne de res 150g, bacon crujiente, queso cheddar y BBQ', prep_time_minutes: 12 },
    { name: 'BBQ Burger', category: 'Burgers', price: 115, description: 'Carne de res 150g, aros de cebolla, queso y salsa BBQ ahumada', prep_time_minutes: 12 },
    { name: 'Mushroom Swiss', category: 'Burgers', price: 120, description: 'Carne de res 150g, champiñones salteados y queso suizo', prep_time_minutes: 12 },
    { name: 'Jalapeño Burger', category: 'Burgers', price: 110, description: 'Carne de res 150g, jalapeños, pepper jack y chipotle mayo', prep_time_minutes: 10 },
    { name: 'Doble Smash', category: 'Burgers', price: 130, description: 'Doble carne smash 2x100g, doble queso, pickles y cebolla caramelizada', prep_time_minutes: 12 },
    { name: 'Chicken Burger', category: 'Burgers', price: 100, description: 'Pechuga empanizada crujiente, lechuga, tomate y mayo', prep_time_minutes: 12 },
    { name: 'Veggie Burger', category: 'Burgers', price: 95, description: 'Hamburguesa de frijol negro y quinoa con aguacate', prep_time_minutes: 10 },
    { name: 'La Mexicana', category: 'Burgers', price: 125, description: 'Carne 150g, guacamole, jalapeños, queso Oaxaca y chipotle', prep_time_minutes: 12 },
    // Sides
    { name: 'Papas a la Francesa', category: 'Sides', price: 45, description: 'Papas fritas crujientes con sal', prep_time_minutes: 6 },
    { name: 'Papas con Queso', category: 'Sides', price: 55, description: 'Papas fritas bañadas en salsa de queso cheddar', prep_time_minutes: 7 },
    { name: 'Aros de Cebolla', category: 'Sides', price: 50, description: 'Aros de cebolla empanizados y crujientes', prep_time_minutes: 6 },
    { name: 'Coleslaw', category: 'Sides', price: 35, description: 'Ensalada fresca de col con aderezo cremoso', prep_time_minutes: 2 },
    { name: 'Nuggets (8 pzas)', category: 'Sides', price: 55, description: 'Nuggets de pollo crujientes con dip', prep_time_minutes: 7 },
    // Drinks
    { name: 'Refresco', category: 'Drinks', price: 30, description: 'Coca-Cola, Sprite o Fanta (500ml)', prep_time_minutes: 1 },
    { name: 'Agua Natural', category: 'Drinks', price: 25, description: 'Agua embotellada (500ml)', prep_time_minutes: 1 },
    { name: 'Limonada', category: 'Drinks', price: 35, description: 'Limonada natural recién exprimida', prep_time_minutes: 3 },
    { name: 'Té Helado', category: 'Drinks', price: 35, description: 'Té negro helado con limón', prep_time_minutes: 2 },
    { name: 'Cerveza Artesanal', category: 'Drinks', price: 65, description: 'Cerveza artesanal local del día', prep_time_minutes: 1 },
    // Shakes
    { name: 'Malteada de Chocolate', category: 'Shakes', price: 65, description: 'Malteada cremosa de chocolate con crema batida', prep_time_minutes: 5 },
    { name: 'Malteada de Vainilla', category: 'Shakes', price: 60, description: 'Malteada clásica de vainilla con crema batida', prep_time_minutes: 5 },
    { name: 'Malteada de Fresa', category: 'Shakes', price: 65, description: 'Malteada de fresa natural con crema batida', prep_time_minutes: 5 },
    { name: 'Malteada Oreo', category: 'Shakes', price: 70, description: 'Malteada de vainilla con galletas Oreo trituradas', prep_time_minutes: 5 },
    // Kids
    { name: 'Mini Burger', category: 'Kids', price: 65, description: 'Hamburguesa pequeña con queso, sin picante', prep_time_minutes: 8 },
    { name: 'Chicken Fingers', category: 'Kids', price: 60, description: 'Tiras de pollo empanizadas con papas', prep_time_minutes: 8 },
    { name: 'Mini Hot Dog', category: 'Kids', price: 55, description: 'Hot dog pequeño con papas fritas', prep_time_minutes: 6 },
  ],

  inventory: [
    { name: 'Carne Molida de Res', unit: 'kg', quantity: 25, low_stock_threshold: 6, category: 'Carnes', cost_price: 180 },
    { name: 'Pechuga de Pollo', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Carnes', cost_price: 110 },
    { name: 'Tocino', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Carnes', cost_price: 200 },
    { name: 'Salchicha Hot Dog', unit: 'pza', quantity: 30, low_stock_threshold: 10, category: 'Carnes', cost_price: 8 },
    { name: 'Pan para Hamburguesa', unit: 'pza', quantity: 80, low_stock_threshold: 20, category: 'Pan', cost_price: 7 },
    { name: 'Pan para Hot Dog', unit: 'pza', quantity: 30, low_stock_threshold: 10, category: 'Pan', cost_price: 5 },
    { name: 'Queso Cheddar (rebanadas)', unit: 'pza', quantity: 100, low_stock_threshold: 25, category: 'Lácteos', cost_price: 4 },
    { name: 'Queso Suizo (rebanadas)', unit: 'pza', quantity: 40, low_stock_threshold: 10, category: 'Lácteos', cost_price: 5 },
    { name: 'Queso Pepper Jack (rebanadas)', unit: 'pza', quantity: 40, low_stock_threshold: 10, category: 'Lácteos', cost_price: 5 },
    { name: 'Queso Oaxaca', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Lácteos', cost_price: 130 },
    { name: 'Lechuga', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 25 },
    { name: 'Tomate', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 30 },
    { name: 'Cebolla', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 18 },
    { name: 'Pepinillos', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 65 },
    { name: 'Jalapeños', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 25 },
    { name: 'Champiñones', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 65 },
    { name: 'Aguacate', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 80 },
    { name: 'Papas para Freír', unit: 'kg', quantity: 20, low_stock_threshold: 5, category: 'Verduras', cost_price: 22 },
    { name: 'Col', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 15 },
    { name: 'Salsa BBQ', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Salsas', cost_price: 55 },
    { name: 'Mayonesa', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Salsas', cost_price: 40 },
    { name: 'Salsa Chipotle', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 50 },
    { name: 'Salsa de Queso Cheddar', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Salsas', cost_price: 60 },
    { name: 'Helado de Vainilla', unit: 'lt', quantity: 5, low_stock_threshold: 1.5, category: 'Lácteos', cost_price: 80 },
    { name: 'Helado de Chocolate', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Lácteos', cost_price: 80 },
    { name: 'Helado de Fresa', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Lácteos', cost_price: 80 },
    { name: 'Leche', unit: 'lt', quantity: 10, low_stock_threshold: 3, category: 'Lácteos', cost_price: 25 },
    { name: 'Galletas Oreo', unit: 'pza', quantity: 50, low_stock_threshold: 15, category: 'Insumos', cost_price: 2 },
    { name: 'Aceite para Freír', unit: 'lt', quantity: 15, low_stock_threshold: 4, category: 'Insumos', cost_price: 35 },
    { name: 'Empanizador', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Insumos', cost_price: 45 },
    { name: 'Frijol Negro', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Granos', cost_price: 30 },
    { name: 'Quinoa', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Granos', cost_price: 90 },
  ],

  recipes: [
    // Clásica
    { item_name: 'Clásica', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'Clásica', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Clásica', ingredient_name: 'Lechuga', quantity_used: 0.03 },
    { item_name: 'Clásica', ingredient_name: 'Tomate', quantity_used: 0.04 },
    { item_name: 'Clásica', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    { item_name: 'Clásica', ingredient_name: 'Mayonesa', quantity_used: 0.02 },
    // Cheese Burger
    { item_name: 'Cheese Burger', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'Cheese Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Cheese Burger', ingredient_name: 'Queso Cheddar (rebanadas)', quantity_used: 1 },
    { item_name: 'Cheese Burger', ingredient_name: 'Lechuga', quantity_used: 0.03 },
    { item_name: 'Cheese Burger', ingredient_name: 'Tomate', quantity_used: 0.04 },
    { item_name: 'Cheese Burger', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    // Bacon Burger
    { item_name: 'Bacon Burger', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'Bacon Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Bacon Burger', ingredient_name: 'Tocino', quantity_used: 0.04 },
    { item_name: 'Bacon Burger', ingredient_name: 'Queso Cheddar (rebanadas)', quantity_used: 1 },
    { item_name: 'Bacon Burger', ingredient_name: 'Salsa BBQ', quantity_used: 0.02 },
    // BBQ Burger
    { item_name: 'BBQ Burger', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'BBQ Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'BBQ Burger', ingredient_name: 'Cebolla', quantity_used: 0.05 },
    { item_name: 'BBQ Burger', ingredient_name: 'Salsa BBQ', quantity_used: 0.03 },
    { item_name: 'BBQ Burger', ingredient_name: 'Queso Cheddar (rebanadas)', quantity_used: 1 },
    // Mushroom Swiss
    { item_name: 'Mushroom Swiss', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'Mushroom Swiss', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Mushroom Swiss', ingredient_name: 'Champiñones', quantity_used: 0.06 },
    { item_name: 'Mushroom Swiss', ingredient_name: 'Queso Suizo (rebanadas)', quantity_used: 1 },
    // Jalapeño Burger
    { item_name: 'Jalapeño Burger', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'Jalapeño Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Jalapeño Burger', ingredient_name: 'Jalapeños', quantity_used: 0.03 },
    { item_name: 'Jalapeño Burger', ingredient_name: 'Queso Pepper Jack (rebanadas)', quantity_used: 1 },
    { item_name: 'Jalapeño Burger', ingredient_name: 'Salsa Chipotle', quantity_used: 0.02 },
    // Doble Smash
    { item_name: 'Doble Smash', ingredient_name: 'Carne Molida de Res', quantity_used: 0.20 },
    { item_name: 'Doble Smash', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Doble Smash', ingredient_name: 'Queso Cheddar (rebanadas)', quantity_used: 2 },
    { item_name: 'Doble Smash', ingredient_name: 'Pepinillos', quantity_used: 0.03 },
    { item_name: 'Doble Smash', ingredient_name: 'Cebolla', quantity_used: 0.04 },
    // Chicken Burger
    { item_name: 'Chicken Burger', ingredient_name: 'Pechuga de Pollo', quantity_used: 0.15 },
    { item_name: 'Chicken Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Chicken Burger', ingredient_name: 'Empanizador', quantity_used: 0.04 },
    { item_name: 'Chicken Burger', ingredient_name: 'Lechuga', quantity_used: 0.03 },
    { item_name: 'Chicken Burger', ingredient_name: 'Tomate', quantity_used: 0.04 },
    { item_name: 'Chicken Burger', ingredient_name: 'Mayonesa', quantity_used: 0.02 },
    // Veggie Burger
    { item_name: 'Veggie Burger', ingredient_name: 'Frijol Negro', quantity_used: 0.08 },
    { item_name: 'Veggie Burger', ingredient_name: 'Quinoa', quantity_used: 0.04 },
    { item_name: 'Veggie Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Veggie Burger', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'Veggie Burger', ingredient_name: 'Lechuga', quantity_used: 0.03 },
    { item_name: 'Veggie Burger', ingredient_name: 'Tomate', quantity_used: 0.04 },
    // La Mexicana
    { item_name: 'La Mexicana', ingredient_name: 'Carne Molida de Res', quantity_used: 0.15 },
    { item_name: 'La Mexicana', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'La Mexicana', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'La Mexicana', ingredient_name: 'Jalapeños', quantity_used: 0.03 },
    { item_name: 'La Mexicana', ingredient_name: 'Queso Oaxaca', quantity_used: 0.05 },
    { item_name: 'La Mexicana', ingredient_name: 'Salsa Chipotle', quantity_used: 0.02 },
    // Papas a la Francesa
    { item_name: 'Papas a la Francesa', ingredient_name: 'Papas para Freír', quantity_used: 0.20 },
    { item_name: 'Papas a la Francesa', ingredient_name: 'Aceite para Freír', quantity_used: 0.05 },
    // Papas con Queso
    { item_name: 'Papas con Queso', ingredient_name: 'Papas para Freír', quantity_used: 0.20 },
    { item_name: 'Papas con Queso', ingredient_name: 'Aceite para Freír', quantity_used: 0.05 },
    { item_name: 'Papas con Queso', ingredient_name: 'Salsa de Queso Cheddar', quantity_used: 0.06 },
    // Aros de Cebolla
    { item_name: 'Aros de Cebolla', ingredient_name: 'Cebolla', quantity_used: 0.15 },
    { item_name: 'Aros de Cebolla', ingredient_name: 'Empanizador', quantity_used: 0.05 },
    { item_name: 'Aros de Cebolla', ingredient_name: 'Aceite para Freír', quantity_used: 0.05 },
    // Nuggets
    { item_name: 'Nuggets (8 pzas)', ingredient_name: 'Pechuga de Pollo', quantity_used: 0.15 },
    { item_name: 'Nuggets (8 pzas)', ingredient_name: 'Empanizador', quantity_used: 0.04 },
    { item_name: 'Nuggets (8 pzas)', ingredient_name: 'Aceite para Freír', quantity_used: 0.05 },
    // Shakes
    { item_name: 'Malteada de Chocolate', ingredient_name: 'Helado de Chocolate', quantity_used: 0.20 },
    { item_name: 'Malteada de Chocolate', ingredient_name: 'Leche', quantity_used: 0.15 },
    { item_name: 'Malteada de Vainilla', ingredient_name: 'Helado de Vainilla', quantity_used: 0.20 },
    { item_name: 'Malteada de Vainilla', ingredient_name: 'Leche', quantity_used: 0.15 },
    { item_name: 'Malteada de Fresa', ingredient_name: 'Helado de Fresa', quantity_used: 0.20 },
    { item_name: 'Malteada de Fresa', ingredient_name: 'Leche', quantity_used: 0.15 },
    { item_name: 'Malteada Oreo', ingredient_name: 'Helado de Vainilla', quantity_used: 0.20 },
    { item_name: 'Malteada Oreo', ingredient_name: 'Leche', quantity_used: 0.15 },
    { item_name: 'Malteada Oreo', ingredient_name: 'Galletas Oreo', quantity_used: 4 },
    // Kids
    { item_name: 'Mini Burger', ingredient_name: 'Carne Molida de Res', quantity_used: 0.08 },
    { item_name: 'Mini Burger', ingredient_name: 'Pan para Hamburguesa', quantity_used: 1 },
    { item_name: 'Mini Burger', ingredient_name: 'Queso Cheddar (rebanadas)', quantity_used: 1 },
    { item_name: 'Chicken Fingers', ingredient_name: 'Pechuga de Pollo', quantity_used: 0.12 },
    { item_name: 'Chicken Fingers', ingredient_name: 'Empanizador', quantity_used: 0.04 },
    { item_name: 'Chicken Fingers', ingredient_name: 'Papas para Freír', quantity_used: 0.10 },
    { item_name: 'Mini Hot Dog', ingredient_name: 'Salchicha Hot Dog', quantity_used: 1 },
    { item_name: 'Mini Hot Dog', ingredient_name: 'Pan para Hot Dog', quantity_used: 1 },
    { item_name: 'Mini Hot Dog', ingredient_name: 'Papas para Freír', quantity_used: 0.10 },
  ],

  modifier_groups: [
    {
      name: 'Patty',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Sencilla', price_adjustment: 0 },
        { name: 'Doble', price_adjustment: 35 },
        { name: 'Triple', price_adjustment: 55 },
      ],
      assign_to_categories: ['Burgers'],
    },
    {
      name: 'Cheese',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Cheddar', price_adjustment: 0 },
        { name: 'Suizo', price_adjustment: 0 },
        { name: 'Pepper Jack', price_adjustment: 0 },
        { name: 'Sin Queso', price_adjustment: 0 },
      ],
      assign_to_categories: ['Burgers'],
    },
    {
      name: 'Extras',
      selection_type: 'multiple',
      required: false,
      min_selections: 0,
      max_selections: 4,
      modifiers: [
        { name: 'Bacon', price_adjustment: 20 },
        { name: 'Jalapeños', price_adjustment: 10 },
        { name: 'Extra Patty', price_adjustment: 45 },
        { name: 'Guacamole', price_adjustment: 18 },
        { name: 'Huevo Frito', price_adjustment: 15 },
        { name: 'Champiñones', price_adjustment: 12 },
      ],
      assign_to_categories: ['Burgers'],
    },
  ],

  combos: [
    {
      name: 'Combo Clásico',
      description: 'Hamburguesa + papas + bebida',
      combo_price: 135,
      slots: [
        { slot_label: 'Hamburguesa', category: 'Burgers' },
        { slot_label: 'Acompañamiento', category: 'Sides' },
        { slot_label: 'Bebida', category: 'Drinks' },
      ],
    },
    {
      name: 'Combo Kids',
      description: 'Plato kids + papas + bebida',
      combo_price: 95,
      slots: [
        { slot_label: 'Plato Kids', category: 'Kids' },
        { slot_label: 'Bebida', category: 'Drinks' },
      ],
    },
  ],
};
