export default {
  id: 'coffee',
  name: 'Coffee Shop / Bakery',
  description: 'Cafeteria artesanal con panaderia y reposteria',
  icon: 'coffee',

  categories: [
    { name: 'Cafe', sort_order: 1 },
    { name: 'Bebidas Frias', sort_order: 2 },
    { name: 'Panaderia', sort_order: 3 },
    { name: 'Snacks', sort_order: 4 },
    { name: 'Postres', sort_order: 5 },
  ],

  items: [
    // Cafe
    { name: 'Americano', category: 'Cafe', price: 40, description: 'Espresso doble con agua caliente', prep_time_minutes: 3 },
    { name: 'Espresso', category: 'Cafe', price: 35, description: 'Shot doble de espresso', prep_time_minutes: 2 },
    { name: 'Cappuccino', category: 'Cafe', price: 50, description: 'Espresso con leche vaporizada y espuma', prep_time_minutes: 4 },
    { name: 'Latte', category: 'Cafe', price: 55, description: 'Espresso con leche vaporizada cremosa', prep_time_minutes: 4 },
    { name: 'Mocha', category: 'Cafe', price: 60, description: 'Espresso con chocolate, leche y crema batida', prep_time_minutes: 5 },
    { name: 'Chai Latte', category: 'Cafe', price: 55, description: 'Te chai con leche vaporizada y especias', prep_time_minutes: 5 },
    { name: 'Matcha Latte', category: 'Cafe', price: 65, description: 'Te matcha ceremonial con leche vaporizada', prep_time_minutes: 4 },
    { name: 'Chocolate Caliente', category: 'Cafe', price: 50, description: 'Chocolate artesanal con leche y malvavisco', prep_time_minutes: 4 },
    // Bebidas Frias
    { name: 'Cafe Helado', category: 'Bebidas Frias', price: 50, description: 'Cold brew con hielo', prep_time_minutes: 2 },
    { name: 'Frappe de Mocha', category: 'Bebidas Frias', price: 65, description: 'Frappe de cafe con chocolate y crema batida', prep_time_minutes: 5 },
    { name: 'Frappe de Caramelo', category: 'Bebidas Frias', price: 65, description: 'Frappe de cafe con caramelo y crema batida', prep_time_minutes: 5 },
    { name: 'Frappe de Vainilla', category: 'Bebidas Frias', price: 60, description: 'Frappe de cafe con vainilla y crema batida', prep_time_minutes: 5 },
    { name: 'Limonada de Fresa', category: 'Bebidas Frias', price: 50, description: 'Limonada natural con fresas frescas', prep_time_minutes: 4 },
    { name: 'Smoothie Verde', category: 'Bebidas Frias', price: 60, description: 'Espinaca, platano, manzana verde y jengibre', prep_time_minutes: 5 },
    { name: 'Te Helado de Durazno', category: 'Bebidas Frias', price: 45, description: 'Te negro helado con durazno natural', prep_time_minutes: 3 },
    // Panaderia
    { name: 'Concha', category: 'Panaderia', price: 18, description: 'Pan dulce clasico de vainilla o chocolate', prep_time_minutes: 1 },
    { name: 'Cuerno de Mantequilla', category: 'Panaderia', price: 30, description: 'Croissant de mantequilla recien horneado', prep_time_minutes: 2 },
    { name: 'Cuerno de Jamon y Queso', category: 'Panaderia', price: 45, description: 'Croissant relleno de jamon y queso gratinado', prep_time_minutes: 5 },
    { name: 'Muffin de Arandano', category: 'Panaderia', price: 35, description: 'Muffin esponjoso con arandanos frescos', prep_time_minutes: 1 },
    { name: 'Muffin de Chocolate', category: 'Panaderia', price: 35, description: 'Muffin de chocolate con chispas', prep_time_minutes: 1 },
    { name: 'Pan de Platano', category: 'Panaderia', price: 30, description: 'Rebanada de pan de platano con nuez', prep_time_minutes: 1 },
    { name: 'Bagel con Queso Crema', category: 'Panaderia', price: 40, description: 'Bagel tostado con queso crema untado', prep_time_minutes: 3 },
    // Snacks
    { name: 'Sandwich de Pollo', category: 'Snacks', price: 65, description: 'Sandwich en ciabatta con pollo, pesto y tomate', prep_time_minutes: 7 },
    { name: 'Sandwich de Jamon', category: 'Snacks', price: 55, description: 'Sandwich de jamon con queso manchego y espinaca', prep_time_minutes: 5 },
    { name: 'Panini Caprese', category: 'Snacks', price: 60, description: 'Panini con mozzarella, tomate, albahaca y pesto', prep_time_minutes: 6 },
    { name: 'Wrap de Pollo', category: 'Snacks', price: 65, description: 'Wrap integral con pollo, lechuga, tomate y aderezo ranch', prep_time_minutes: 6 },
    { name: 'Ensalada de Frutas', category: 'Snacks', price: 45, description: 'Frutas de temporada con granola y yogurt', prep_time_minutes: 4 },
    // Postres
    { name: 'Cheesecake', category: 'Postres', price: 55, description: 'Rebanada de cheesecake New York con frutos rojos', prep_time_minutes: 2 },
    { name: 'Brownie', category: 'Postres', price: 40, description: 'Brownie de chocolate intenso con nuez', prep_time_minutes: 2 },
    { name: 'Galleta de Chispas', category: 'Postres', price: 25, description: 'Galleta grande de chispas de chocolate', prep_time_minutes: 1 },
    { name: 'Rol de Canela', category: 'Postres', price: 45, description: 'Rol de canela glaseado recien horneado', prep_time_minutes: 3 },
    { name: 'Pastel de Zanahoria', category: 'Postres', price: 55, description: 'Rebanada de pastel de zanahoria con frosting de queso crema', prep_time_minutes: 2 },
  ],

  inventory: [
    { name: 'Cafe en Grano', unit: 'kg', quantity: 15, low_stock_threshold: 4, category: 'Cafe', cost_price: 350 },
    { name: 'Leche Entera', unit: 'lt', quantity: 30, low_stock_threshold: 8, category: 'Lacteos', cost_price: 25 },
    { name: 'Leche Deslactosada', unit: 'lt', quantity: 10, low_stock_threshold: 3, category: 'Lacteos', cost_price: 30 },
    { name: 'Leche de Avena', unit: 'lt', quantity: 8, low_stock_threshold: 2, category: 'Lacteos', cost_price: 55 },
    { name: 'Leche de Almendra', unit: 'lt', quantity: 8, low_stock_threshold: 2, category: 'Lacteos', cost_price: 60 },
    { name: 'Chocolate en Polvo', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Insumos', cost_price: 120 },
    { name: 'Jarabe de Vainilla', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Jarabes', cost_price: 80 },
    { name: 'Jarabe de Caramelo', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Jarabes', cost_price: 80 },
    { name: 'Jarabe de Avellana', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Jarabes', cost_price: 85 },
    { name: 'Polvo de Matcha', unit: 'kg', quantity: 0.5, low_stock_threshold: 0.15, category: 'Cafe', cost_price: 800 },
    { name: 'Te Chai Concentrado', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Cafe', cost_price: 100 },
    { name: 'Crema Batida', unit: 'lt', quantity: 5, low_stock_threshold: 1.5, category: 'Lacteos', cost_price: 60 },
    { name: 'Azucar', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Insumos', cost_price: 25 },
    { name: 'Harina', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Panaderia', cost_price: 18 },
    { name: 'Mantequilla', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Panaderia', cost_price: 120 },
    { name: 'Huevos', unit: 'pza', quantity: 90, low_stock_threshold: 24, category: 'Panaderia', cost_price: 4 },
    { name: 'Arandanos', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Frutas', cost_price: 180 },
    { name: 'Fresas', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Frutas', cost_price: 60 },
    { name: 'Platano', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Frutas', cost_price: 18 },
    { name: 'Queso Crema', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Lacteos', cost_price: 90 },
    { name: 'Jamon', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 110 },
    { name: 'Pollo Cocido', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 120 },
    { name: 'Mozzarella', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Lacteos', cost_price: 120 },
    { name: 'Queso Manchego', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Lacteos', cost_price: 130 },
    { name: 'Pan Ciabatta', unit: 'pza', quantity: 20, low_stock_threshold: 5, category: 'Pan', cost_price: 10 },
    { name: 'Pan para Panini', unit: 'pza', quantity: 20, low_stock_threshold: 5, category: 'Pan', cost_price: 8 },
    { name: 'Tortilla Integral (Wrap)', unit: 'pza', quantity: 20, low_stock_threshold: 5, category: 'Pan', cost_price: 6 },
    { name: 'Bagels', unit: 'pza', quantity: 20, low_stock_threshold: 5, category: 'Pan', cost_price: 8 },
    { name: 'Pesto', unit: 'lt', quantity: 1, low_stock_threshold: 0.3, category: 'Salsas', cost_price: 120 },
    { name: 'Espinaca', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 40 },
    { name: 'Tomate', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 30 },
    { name: 'Lechuga', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 25 },
    { name: 'Granola', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Insumos', cost_price: 80 },
    { name: 'Yogurt Natural', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Lacteos', cost_price: 40 },
    { name: 'Nuez', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Insumos', cost_price: 280 },
    { name: 'Canela', unit: 'kg', quantity: 0.5, low_stock_threshold: 0.1, category: 'Insumos', cost_price: 200 },
    { name: 'Te Negro', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Cafe', cost_price: 250 },
    { name: 'Durazno', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Frutas', cost_price: 45 },
  ],

  recipes: [
    // Americano
    { item_name: 'Americano', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    // Espresso
    { item_name: 'Espresso', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    // Cappuccino
    { item_name: 'Cappuccino', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Cappuccino', ingredient_name: 'Leche Entera', quantity_used: 0.15 },
    // Latte
    { item_name: 'Latte', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Latte', ingredient_name: 'Leche Entera', quantity_used: 0.25 },
    // Mocha
    { item_name: 'Mocha', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Mocha', ingredient_name: 'Leche Entera', quantity_used: 0.20 },
    { item_name: 'Mocha', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.02 },
    { item_name: 'Mocha', ingredient_name: 'Crema Batida', quantity_used: 0.03 },
    // Chai Latte
    { item_name: 'Chai Latte', ingredient_name: 'Te Chai Concentrado', quantity_used: 0.10 },
    { item_name: 'Chai Latte', ingredient_name: 'Leche Entera', quantity_used: 0.20 },
    // Matcha Latte
    { item_name: 'Matcha Latte', ingredient_name: 'Polvo de Matcha', quantity_used: 0.004 },
    { item_name: 'Matcha Latte', ingredient_name: 'Leche Entera', quantity_used: 0.25 },
    // Chocolate Caliente
    { item_name: 'Chocolate Caliente', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.03 },
    { item_name: 'Chocolate Caliente', ingredient_name: 'Leche Entera', quantity_used: 0.25 },
    // Cafe Helado
    { item_name: 'Cafe Helado', ingredient_name: 'Cafe en Grano', quantity_used: 0.025 },
    // Frappe de Mocha
    { item_name: 'Frappe de Mocha', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Frappe de Mocha', ingredient_name: 'Leche Entera', quantity_used: 0.20 },
    { item_name: 'Frappe de Mocha', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.02 },
    { item_name: 'Frappe de Mocha', ingredient_name: 'Crema Batida', quantity_used: 0.03 },
    // Frappe de Caramelo
    { item_name: 'Frappe de Caramelo', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Frappe de Caramelo', ingredient_name: 'Leche Entera', quantity_used: 0.20 },
    { item_name: 'Frappe de Caramelo', ingredient_name: 'Jarabe de Caramelo', quantity_used: 0.03 },
    { item_name: 'Frappe de Caramelo', ingredient_name: 'Crema Batida', quantity_used: 0.03 },
    // Frappe de Vainilla
    { item_name: 'Frappe de Vainilla', ingredient_name: 'Cafe en Grano', quantity_used: 0.018 },
    { item_name: 'Frappe de Vainilla', ingredient_name: 'Leche Entera', quantity_used: 0.20 },
    { item_name: 'Frappe de Vainilla', ingredient_name: 'Jarabe de Vainilla', quantity_used: 0.03 },
    { item_name: 'Frappe de Vainilla', ingredient_name: 'Crema Batida', quantity_used: 0.03 },
    // Limonada de Fresa
    { item_name: 'Limonada de Fresa', ingredient_name: 'Fresas', quantity_used: 0.08 },
    { item_name: 'Limonada de Fresa', ingredient_name: 'Azucar', quantity_used: 0.03 },
    // Smoothie Verde
    { item_name: 'Smoothie Verde', ingredient_name: 'Espinaca', quantity_used: 0.05 },
    { item_name: 'Smoothie Verde', ingredient_name: 'Platano', quantity_used: 0.10 },
    // Te Helado de Durazno
    { item_name: 'Te Helado de Durazno', ingredient_name: 'Te Negro', quantity_used: 0.005 },
    { item_name: 'Te Helado de Durazno', ingredient_name: 'Durazno', quantity_used: 0.06 },
    { item_name: 'Te Helado de Durazno', ingredient_name: 'Azucar', quantity_used: 0.02 },
    // Panaderia
    { item_name: 'Concha', ingredient_name: 'Harina', quantity_used: 0.08 },
    { item_name: 'Concha', ingredient_name: 'Mantequilla', quantity_used: 0.02 },
    { item_name: 'Concha', ingredient_name: 'Azucar', quantity_used: 0.02 },
    { item_name: 'Cuerno de Mantequilla', ingredient_name: 'Harina', quantity_used: 0.08 },
    { item_name: 'Cuerno de Mantequilla', ingredient_name: 'Mantequilla', quantity_used: 0.04 },
    { item_name: 'Cuerno de Jamon y Queso', ingredient_name: 'Harina', quantity_used: 0.08 },
    { item_name: 'Cuerno de Jamon y Queso', ingredient_name: 'Mantequilla', quantity_used: 0.04 },
    { item_name: 'Cuerno de Jamon y Queso', ingredient_name: 'Jamon', quantity_used: 0.04 },
    { item_name: 'Cuerno de Jamon y Queso', ingredient_name: 'Queso Manchego', quantity_used: 0.03 },
    { item_name: 'Muffin de Arandano', ingredient_name: 'Harina', quantity_used: 0.06 },
    { item_name: 'Muffin de Arandano', ingredient_name: 'Mantequilla', quantity_used: 0.02 },
    { item_name: 'Muffin de Arandano', ingredient_name: 'Huevos', quantity_used: 1 },
    { item_name: 'Muffin de Arandano', ingredient_name: 'Arandanos', quantity_used: 0.04 },
    { item_name: 'Muffin de Chocolate', ingredient_name: 'Harina', quantity_used: 0.06 },
    { item_name: 'Muffin de Chocolate', ingredient_name: 'Mantequilla', quantity_used: 0.02 },
    { item_name: 'Muffin de Chocolate', ingredient_name: 'Huevos', quantity_used: 1 },
    { item_name: 'Muffin de Chocolate', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.02 },
    { item_name: 'Pan de Platano', ingredient_name: 'Harina', quantity_used: 0.06 },
    { item_name: 'Pan de Platano', ingredient_name: 'Platano', quantity_used: 0.10 },
    { item_name: 'Pan de Platano', ingredient_name: 'Nuez', quantity_used: 0.02 },
    { item_name: 'Pan de Platano', ingredient_name: 'Huevos', quantity_used: 0.5 },
    { item_name: 'Bagel con Queso Crema', ingredient_name: 'Bagels', quantity_used: 1 },
    { item_name: 'Bagel con Queso Crema', ingredient_name: 'Queso Crema', quantity_used: 0.04 },
    // Snacks
    { item_name: 'Sandwich de Pollo', ingredient_name: 'Pan Ciabatta', quantity_used: 1 },
    { item_name: 'Sandwich de Pollo', ingredient_name: 'Pollo Cocido', quantity_used: 0.10 },
    { item_name: 'Sandwich de Pollo', ingredient_name: 'Pesto', quantity_used: 0.02 },
    { item_name: 'Sandwich de Pollo', ingredient_name: 'Tomate', quantity_used: 0.04 },
    { item_name: 'Sandwich de Jamon', ingredient_name: 'Pan Ciabatta', quantity_used: 1 },
    { item_name: 'Sandwich de Jamon', ingredient_name: 'Jamon', quantity_used: 0.06 },
    { item_name: 'Sandwich de Jamon', ingredient_name: 'Queso Manchego', quantity_used: 0.04 },
    { item_name: 'Sandwich de Jamon', ingredient_name: 'Espinaca', quantity_used: 0.02 },
    { item_name: 'Panini Caprese', ingredient_name: 'Pan para Panini', quantity_used: 1 },
    { item_name: 'Panini Caprese', ingredient_name: 'Mozzarella', quantity_used: 0.06 },
    { item_name: 'Panini Caprese', ingredient_name: 'Tomate', quantity_used: 0.06 },
    { item_name: 'Panini Caprese', ingredient_name: 'Pesto', quantity_used: 0.02 },
    { item_name: 'Wrap de Pollo', ingredient_name: 'Tortilla Integral (Wrap)', quantity_used: 1 },
    { item_name: 'Wrap de Pollo', ingredient_name: 'Pollo Cocido', quantity_used: 0.10 },
    { item_name: 'Wrap de Pollo', ingredient_name: 'Lechuga', quantity_used: 0.03 },
    { item_name: 'Wrap de Pollo', ingredient_name: 'Tomate', quantity_used: 0.03 },
    { item_name: 'Ensalada de Frutas', ingredient_name: 'Fresas', quantity_used: 0.06 },
    { item_name: 'Ensalada de Frutas', ingredient_name: 'Platano', quantity_used: 0.08 },
    { item_name: 'Ensalada de Frutas', ingredient_name: 'Granola', quantity_used: 0.03 },
    { item_name: 'Ensalada de Frutas', ingredient_name: 'Yogurt Natural', quantity_used: 0.10 },
    // Postres
    { item_name: 'Cheesecake', ingredient_name: 'Queso Crema', quantity_used: 0.10 },
    { item_name: 'Cheesecake', ingredient_name: 'Huevos', quantity_used: 1 },
    { item_name: 'Cheesecake', ingredient_name: 'Fresas', quantity_used: 0.04 },
    { item_name: 'Brownie', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.04 },
    { item_name: 'Brownie', ingredient_name: 'Mantequilla', quantity_used: 0.04 },
    { item_name: 'Brownie', ingredient_name: 'Huevos', quantity_used: 1 },
    { item_name: 'Brownie', ingredient_name: 'Nuez', quantity_used: 0.02 },
    { item_name: 'Galleta de Chispas', ingredient_name: 'Harina', quantity_used: 0.04 },
    { item_name: 'Galleta de Chispas', ingredient_name: 'Mantequilla', quantity_used: 0.02 },
    { item_name: 'Galleta de Chispas', ingredient_name: 'Chocolate en Polvo', quantity_used: 0.02 },
    { item_name: 'Rol de Canela', ingredient_name: 'Harina', quantity_used: 0.10 },
    { item_name: 'Rol de Canela', ingredient_name: 'Mantequilla', quantity_used: 0.04 },
    { item_name: 'Rol de Canela', ingredient_name: 'Canela', quantity_used: 0.003 },
    { item_name: 'Rol de Canela', ingredient_name: 'Azucar', quantity_used: 0.03 },
    { item_name: 'Pastel de Zanahoria', ingredient_name: 'Harina', quantity_used: 0.06 },
    { item_name: 'Pastel de Zanahoria', ingredient_name: 'Huevos', quantity_used: 1 },
    { item_name: 'Pastel de Zanahoria', ingredient_name: 'Queso Crema', quantity_used: 0.04 },
    { item_name: 'Pastel de Zanahoria', ingredient_name: 'Nuez', quantity_used: 0.02 },
  ],

  modifier_groups: [
    {
      name: 'Tamano',
      selection_type: 'single',
      required: true,
      min_selections: 1,
      max_selections: 1,
      modifiers: [
        { name: 'Chico', price_adjustment: 0 },
        { name: 'Mediano', price_adjustment: 10 },
        { name: 'Grande', price_adjustment: 20 },
      ],
      assign_to_categories: ['Cafe', 'Bebidas Frias'],
    },
    {
      name: 'Leche',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Entera', price_adjustment: 0 },
        { name: 'Deslactosada', price_adjustment: 0 },
        { name: 'Avena', price_adjustment: 15 },
        { name: 'Almendra', price_adjustment: 15 },
      ],
      assign_to_categories: ['Cafe', 'Bebidas Frias'],
    },
    {
      name: 'Extras',
      selection_type: 'multiple',
      required: false,
      min_selections: 0,
      max_selections: 3,
      modifiers: [
        { name: 'Shot Extra', price_adjustment: 12 },
        { name: 'Jarabe de Vainilla', price_adjustment: 8 },
        { name: 'Jarabe de Caramelo', price_adjustment: 8 },
        { name: 'Jarabe de Avellana', price_adjustment: 8 },
        { name: 'Crema Batida', price_adjustment: 10 },
      ],
      assign_to_categories: ['Cafe', 'Bebidas Frias'],
    },
  ],

  combos: [
    {
      name: 'Combo Desayuno',
      description: 'Cafe al gusto + pan de la panaderia',
      combo_price: 55,
      slots: [
        { slot_label: 'Cafe', category: 'Cafe' },
        { slot_label: 'Pan', category: 'Panaderia' },
      ],
    },
    {
      name: 'Combo Frappe',
      description: 'Frappe o bebida fria + muffin o postre',
      combo_price: 85,
      slots: [
        { slot_label: 'Bebida Fria', category: 'Bebidas Frias' },
        { slot_label: 'Postre', category: 'Postres' },
      ],
    },
  ],
};
