export default {
  id: 'pizzeria',
  name: 'Pizzeria',
  description: 'Pizzas artesanales, pastas y ensaladas italianas',
  icon: 'pizza',

  categories: [
    { name: 'Pizzas', sort_order: 1 },
    { name: 'Pastas', sort_order: 2 },
    { name: 'Ensaladas', sort_order: 3 },
    { name: 'Bebidas', sort_order: 4 },
    { name: 'Postres', sort_order: 5 },
  ],

  items: [
    // Pizzas (base price = personal size)
    { name: 'Margarita', category: 'Pizzas', price: 120, description: 'Salsa de tomate, mozzarella fresca y albahaca', prep_time_minutes: 15 },
    { name: 'Pepperoni', category: 'Pizzas', price: 140, description: 'Salsa de tomate, mozzarella y pepperoni', prep_time_minutes: 15 },
    { name: 'Hawaiana', category: 'Pizzas', price: 145, description: 'Salsa de tomate, mozzarella, jamón y piña', prep_time_minutes: 15 },
    { name: 'Mexicana', category: 'Pizzas', price: 155, description: 'Salsa de tomate, mozzarella, chorizo, jalapeño y cebolla', prep_time_minutes: 15 },
    { name: 'Quattro Formaggi', category: 'Pizzas', price: 160, description: 'Mozzarella, gorgonzola, parmesano y queso de cabra', prep_time_minutes: 15 },
    { name: 'Suprema', category: 'Pizzas', price: 170, description: 'Pepperoni, champiñones, pimiento, cebolla, aceitunas y salchicha', prep_time_minutes: 18 },
    { name: 'Carnes Frías', category: 'Pizzas', price: 175, description: 'Pepperoni, jamón, tocino, salchicha italiana y carne molida', prep_time_minutes: 18 },
    { name: 'Vegetariana', category: 'Pizzas', price: 145, description: 'Champiñones, pimiento, cebolla, aceitunas, tomate y espinaca', prep_time_minutes: 15 },
    { name: 'BBQ Chicken', category: 'Pizzas', price: 165, description: 'Salsa BBQ, pollo, cebolla morada, cilantro y mozzarella', prep_time_minutes: 16 },
    { name: 'Diavola', category: 'Pizzas', price: 150, description: 'Salsa de tomate, salami picante, chile de árbol y mozzarella', prep_time_minutes: 15 },
    // Pastas
    { name: 'Spaghetti Bolognesa', category: 'Pastas', price: 105, description: 'Spaghetti con salsa bolognesa de carne de res', prep_time_minutes: 12 },
    { name: 'Fettuccine Alfredo', category: 'Pastas', price: 110, description: 'Fettuccine en salsa cremosa de parmesano', prep_time_minutes: 12 },
    { name: 'Penne Arrabbiata', category: 'Pastas', price: 95, description: 'Penne en salsa de tomate picante con ajo', prep_time_minutes: 12 },
    { name: 'Lasaña', category: 'Pastas', price: 130, description: 'Capas de pasta, carne, bechamel y queso gratinado', prep_time_minutes: 20 },
    { name: 'Ravioles de Ricotta', category: 'Pastas', price: 125, description: 'Ravioles rellenos de ricotta y espinaca en salsa de tomate', prep_time_minutes: 14 },
    { name: 'Spaghetti Carbonara', category: 'Pastas', price: 115, description: 'Spaghetti con tocino, huevo, parmesano y pimienta negra', prep_time_minutes: 12 },
    // Ensaladas
    { name: 'Ensalada César', category: 'Ensaladas', price: 75, description: 'Lechuga romana, crutones, parmesano y aderezo César', prep_time_minutes: 5 },
    { name: 'Ensalada Caprese', category: 'Ensaladas', price: 80, description: 'Tomate, mozzarella fresca, albahaca y aceite de oliva', prep_time_minutes: 5 },
    { name: 'Ensalada Mediterránea', category: 'Ensaladas', price: 85, description: 'Lechugas mixtas, aceitunas, pepino, tomate cherry y queso feta', prep_time_minutes: 5 },
    // Bebidas
    { name: 'Refresco', category: 'Bebidas', price: 30, description: 'Coca-Cola, Sprite o Fanta (500ml)', prep_time_minutes: 1 },
    { name: 'Agua Mineral', category: 'Bebidas', price: 28, description: 'Agua mineral con o sin gas', prep_time_minutes: 1 },
    { name: 'Limonada', category: 'Bebidas', price: 35, description: 'Limonada natural', prep_time_minutes: 3 },
    { name: 'Té Helado', category: 'Bebidas', price: 35, description: 'Té helado de durazno o limón', prep_time_minutes: 2 },
    { name: 'Cerveza', category: 'Bebidas', price: 45, description: 'Cerveza importada italiana (330ml)', prep_time_minutes: 1 },
    // Postres
    { name: 'Tiramisú', category: 'Postres', price: 65, description: 'Tiramisú clásico con mascarpone y café', prep_time_minutes: 3 },
    { name: 'Cannoli', category: 'Postres', price: 55, description: 'Cannoli siciliano relleno de ricotta dulce', prep_time_minutes: 3 },
    { name: 'Panna Cotta', category: 'Postres', price: 60, description: 'Panna cotta de vainilla con coulis de frutos rojos', prep_time_minutes: 3 },
    { name: 'Brownie con Helado', category: 'Postres', price: 65, description: 'Brownie tibio de chocolate con helado de vainilla', prep_time_minutes: 5 },
  ],

  inventory: [
    { name: 'Masa para Pizza', unit: 'pza', quantity: 60, low_stock_threshold: 15, category: 'Masas', cost_price: 12 },
    { name: 'Queso Mozzarella', unit: 'kg', quantity: 15, low_stock_threshold: 4, category: 'Lácteos', cost_price: 120 },
    { name: 'Salsa de Tomate Pizza', unit: 'lt', quantity: 10, low_stock_threshold: 3, category: 'Salsas', cost_price: 30 },
    { name: 'Pepperoni', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Carnes', cost_price: 160 },
    { name: 'Jamón', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Carnes', cost_price: 110 },
    { name: 'Tocino', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 200 },
    { name: 'Salchicha Italiana', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 140 },
    { name: 'Salami Picante', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Carnes', cost_price: 180 },
    { name: 'Carne Molida', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Carnes', cost_price: 180 },
    { name: 'Pollo Desmenuzado', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Carnes', cost_price: 110 },
    { name: 'Chorizo', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 120 },
    { name: 'Champiñones', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 65 },
    { name: 'Pimiento Morrón', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 40 },
    { name: 'Cebolla', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 18 },
    { name: 'Aceitunas Negras', unit: 'kg', quantity: 3, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 90 },
    { name: 'Piña en Trozos', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 25 },
    { name: 'Jalapeños', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 25 },
    { name: 'Espinaca', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 40 },
    { name: 'Tomate', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 30 },
    { name: 'Albahaca', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Verduras', cost_price: 80 },
    { name: 'Lechuga Romana', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 25 },
    { name: 'Queso Parmesano', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Lácteos', cost_price: 250 },
    { name: 'Queso Gorgonzola', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Lácteos', cost_price: 280 },
    { name: 'Queso de Cabra', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Lácteos', cost_price: 200 },
    { name: 'Queso Feta', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Lácteos', cost_price: 180 },
    { name: 'Ricotta', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Lácteos', cost_price: 100 },
    { name: 'Mascarpone', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Lácteos', cost_price: 180 },
    { name: 'Crema para Cocinar', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Lácteos', cost_price: 50 },
    { name: 'Spaghetti Seco', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Pastas', cost_price: 35 },
    { name: 'Fettuccine Seco', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Pastas', cost_price: 38 },
    { name: 'Penne Seco', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Pastas', cost_price: 35 },
    { name: 'Láminas de Lasaña', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Pastas', cost_price: 45 },
    { name: 'Ravioles de Ricotta', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Pastas', cost_price: 80 },
    { name: 'Salsa BBQ', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 55 },
    { name: 'Aceite de Oliva', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Insumos', cost_price: 100 },
    { name: 'Crutones', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Insumos', cost_price: 60 },
    { name: 'Aderezo César', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 70 },
    { name: 'Pan de Ajo', unit: 'pza', quantity: 40, low_stock_threshold: 10, category: 'Pan', cost_price: 8 },
  ],

  recipes: [
    // Margarita
    { item_name: 'Margarita', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Margarita', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Margarita', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Margarita', ingredient_name: 'Albahaca', quantity_used: 0.01 },
    // Pepperoni
    { item_name: 'Pepperoni', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Pepperoni', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Pepperoni', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Pepperoni', ingredient_name: 'Pepperoni', quantity_used: 0.06 },
    // Hawaiana
    { item_name: 'Hawaiana', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Hawaiana', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Hawaiana', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Hawaiana', ingredient_name: 'Jamón', quantity_used: 0.06 },
    { item_name: 'Hawaiana', ingredient_name: 'Piña en Trozos', quantity_used: 0.06 },
    // Mexicana
    { item_name: 'Mexicana', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Mexicana', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Mexicana', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Mexicana', ingredient_name: 'Chorizo', quantity_used: 0.05 },
    { item_name: 'Mexicana', ingredient_name: 'Jalapeños', quantity_used: 0.03 },
    { item_name: 'Mexicana', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    // Quattro Formaggi
    { item_name: 'Quattro Formaggi', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Quattro Formaggi', ingredient_name: 'Queso Mozzarella', quantity_used: 0.08 },
    { item_name: 'Quattro Formaggi', ingredient_name: 'Queso Gorgonzola', quantity_used: 0.04 },
    { item_name: 'Quattro Formaggi', ingredient_name: 'Queso Parmesano', quantity_used: 0.03 },
    { item_name: 'Quattro Formaggi', ingredient_name: 'Queso de Cabra', quantity_used: 0.04 },
    // Suprema
    { item_name: 'Suprema', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Suprema', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Suprema', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Suprema', ingredient_name: 'Pepperoni', quantity_used: 0.03 },
    { item_name: 'Suprema', ingredient_name: 'Champiñones', quantity_used: 0.03 },
    { item_name: 'Suprema', ingredient_name: 'Pimiento Morrón', quantity_used: 0.03 },
    { item_name: 'Suprema', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    { item_name: 'Suprema', ingredient_name: 'Aceitunas Negras', quantity_used: 0.02 },
    { item_name: 'Suprema', ingredient_name: 'Salchicha Italiana', quantity_used: 0.04 },
    // Carnes Frías
    { item_name: 'Carnes Frías', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Carnes Frías', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Carnes Frías', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Carnes Frías', ingredient_name: 'Pepperoni', quantity_used: 0.03 },
    { item_name: 'Carnes Frías', ingredient_name: 'Jamón', quantity_used: 0.03 },
    { item_name: 'Carnes Frías', ingredient_name: 'Tocino', quantity_used: 0.03 },
    { item_name: 'Carnes Frías', ingredient_name: 'Salchicha Italiana', quantity_used: 0.03 },
    { item_name: 'Carnes Frías', ingredient_name: 'Carne Molida', quantity_used: 0.04 },
    // Vegetariana
    { item_name: 'Vegetariana', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Vegetariana', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Vegetariana', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Vegetariana', ingredient_name: 'Champiñones', quantity_used: 0.03 },
    { item_name: 'Vegetariana', ingredient_name: 'Pimiento Morrón', quantity_used: 0.03 },
    { item_name: 'Vegetariana', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    { item_name: 'Vegetariana', ingredient_name: 'Aceitunas Negras', quantity_used: 0.02 },
    { item_name: 'Vegetariana', ingredient_name: 'Tomate', quantity_used: 0.04 },
    { item_name: 'Vegetariana', ingredient_name: 'Espinaca', quantity_used: 0.03 },
    // BBQ Chicken
    { item_name: 'BBQ Chicken', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'BBQ Chicken', ingredient_name: 'Salsa BBQ', quantity_used: 0.06 },
    { item_name: 'BBQ Chicken', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'BBQ Chicken', ingredient_name: 'Pollo Desmenuzado', quantity_used: 0.08 },
    { item_name: 'BBQ Chicken', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    // Diavola
    { item_name: 'Diavola', ingredient_name: 'Masa para Pizza', quantity_used: 1 },
    { item_name: 'Diavola', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.08 },
    { item_name: 'Diavola', ingredient_name: 'Queso Mozzarella', quantity_used: 0.12 },
    { item_name: 'Diavola', ingredient_name: 'Salami Picante', quantity_used: 0.05 },
    // Pastas
    { item_name: 'Spaghetti Bolognesa', ingredient_name: 'Spaghetti Seco', quantity_used: 0.15 },
    { item_name: 'Spaghetti Bolognesa', ingredient_name: 'Carne Molida', quantity_used: 0.12 },
    { item_name: 'Spaghetti Bolognesa', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.10 },
    { item_name: 'Fettuccine Alfredo', ingredient_name: 'Fettuccine Seco', quantity_used: 0.15 },
    { item_name: 'Fettuccine Alfredo', ingredient_name: 'Crema para Cocinar', quantity_used: 0.10 },
    { item_name: 'Fettuccine Alfredo', ingredient_name: 'Queso Parmesano', quantity_used: 0.04 },
    { item_name: 'Penne Arrabbiata', ingredient_name: 'Penne Seco', quantity_used: 0.15 },
    { item_name: 'Penne Arrabbiata', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.12 },
    { item_name: 'Lasaña', ingredient_name: 'Láminas de Lasaña', quantity_used: 0.15 },
    { item_name: 'Lasaña', ingredient_name: 'Carne Molida', quantity_used: 0.12 },
    { item_name: 'Lasaña', ingredient_name: 'Queso Mozzarella', quantity_used: 0.10 },
    { item_name: 'Lasaña', ingredient_name: 'Crema para Cocinar', quantity_used: 0.08 },
    { item_name: 'Ravioles de Ricotta', ingredient_name: 'Ravioles de Ricotta', quantity_used: 0.20 },
    { item_name: 'Ravioles de Ricotta', ingredient_name: 'Salsa de Tomate Pizza', quantity_used: 0.10 },
    { item_name: 'Spaghetti Carbonara', ingredient_name: 'Spaghetti Seco', quantity_used: 0.15 },
    { item_name: 'Spaghetti Carbonara', ingredient_name: 'Tocino', quantity_used: 0.05 },
    { item_name: 'Spaghetti Carbonara', ingredient_name: 'Queso Parmesano', quantity_used: 0.04 },
    { item_name: 'Spaghetti Carbonara', ingredient_name: 'Crema para Cocinar', quantity_used: 0.05 },
    // Ensaladas
    { item_name: 'Ensalada César', ingredient_name: 'Lechuga Romana', quantity_used: 0.15 },
    { item_name: 'Ensalada César', ingredient_name: 'Crutones', quantity_used: 0.03 },
    { item_name: 'Ensalada César', ingredient_name: 'Queso Parmesano', quantity_used: 0.02 },
    { item_name: 'Ensalada César', ingredient_name: 'Aderezo César', quantity_used: 0.04 },
    { item_name: 'Ensalada Caprese', ingredient_name: 'Tomate', quantity_used: 0.15 },
    { item_name: 'Ensalada Caprese', ingredient_name: 'Queso Mozzarella', quantity_used: 0.10 },
    { item_name: 'Ensalada Caprese', ingredient_name: 'Albahaca', quantity_used: 0.01 },
    { item_name: 'Ensalada Caprese', ingredient_name: 'Aceite de Oliva', quantity_used: 0.02 },
    { item_name: 'Ensalada Mediterránea', ingredient_name: 'Lechuga Romana', quantity_used: 0.10 },
    { item_name: 'Ensalada Mediterránea', ingredient_name: 'Aceitunas Negras', quantity_used: 0.03 },
    { item_name: 'Ensalada Mediterránea', ingredient_name: 'Tomate', quantity_used: 0.06 },
    { item_name: 'Ensalada Mediterránea', ingredient_name: 'Queso Feta', quantity_used: 0.04 },
    { item_name: 'Ensalada Mediterránea', ingredient_name: 'Aceite de Oliva', quantity_used: 0.02 },
  ],

  modifier_groups: [
    {
      name: 'Tamaño',
      selection_type: 'single',
      required: true,
      min_selections: 1,
      max_selections: 1,
      modifiers: [
        { name: 'Personal', price_adjustment: 0 },
        { name: 'Mediana', price_adjustment: 40 },
        { name: 'Grande', price_adjustment: 80 },
        { name: 'Familiar', price_adjustment: 120 },
      ],
      assign_to_categories: ['Pizzas'],
    },
    {
      name: 'Extra Toppings',
      selection_type: 'multiple',
      required: false,
      min_selections: 0,
      max_selections: 5,
      modifiers: [
        { name: 'Pepperoni Extra', price_adjustment: 20 },
        { name: 'Champiñones', price_adjustment: 15 },
        { name: 'Aceitunas', price_adjustment: 15 },
        { name: 'Pimiento Morrón', price_adjustment: 15 },
        { name: 'Jalapeños', price_adjustment: 10 },
        { name: 'Piña', price_adjustment: 15 },
        { name: 'Tocino', price_adjustment: 25 },
        { name: 'Extra Queso', price_adjustment: 20 },
      ],
      assign_to_categories: ['Pizzas'],
    },
    {
      name: 'Acompañamiento',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Pan de Ajo (4 pzas)', price_adjustment: 25 },
        { name: 'Pollo a la Parrilla', price_adjustment: 30 },
      ],
      assign_to_categories: ['Ensaladas'],
    },
  ],

  combos: [
    {
      name: 'Combo Pizza',
      description: 'Pizza al gusto + 2 bebidas',
      combo_price: 175,
      slots: [
        { slot_label: 'Pizza', category: 'Pizzas' },
        { slot_label: 'Bebida 1', category: 'Bebidas' },
        { slot_label: 'Bebida 2', category: 'Bebidas' },
      ],
    },
    {
      name: 'Combo Pasta',
      description: 'Pasta al gusto + pan de ajo + bebida',
      combo_price: 145,
      slots: [
        { slot_label: 'Pasta', category: 'Pastas' },
        { slot_label: 'Bebida', category: 'Bebidas' },
      ],
    },
  ],
};
