export default {
  id: 'sushi',
  name: 'Sushi / Japanese',
  description: 'Sushi rolls, nigiri, entradas japonesas y sopas',
  icon: 'sushi',

  categories: [
    { name: 'Rolls', sort_order: 1 },
    { name: 'Nigiri', sort_order: 2 },
    { name: 'Entradas', sort_order: 3 },
    { name: 'Sopas', sort_order: 4 },
    { name: 'Bebidas', sort_order: 5 },
  ],

  items: [
    // Rolls
    { name: 'California Roll', category: 'Rolls', price: 110, description: 'Surimi, aguacate y pepino con ajonjoli', prep_time_minutes: 10 },
    { name: 'Salmon Roll', category: 'Rolls', price: 135, description: 'Salmon fresco, aguacate y queso crema', prep_time_minutes: 10 },
    { name: 'Philadelphia Roll', category: 'Rolls', price: 130, description: 'Salmon ahumado, queso crema y pepino', prep_time_minutes: 10 },
    { name: 'Spicy Tuna Roll', category: 'Rolls', price: 140, description: 'Atun picante, pepino y cebolleta con salsa sriracha', prep_time_minutes: 10 },
    { name: 'Dragon Roll', category: 'Rolls', price: 170, description: 'Tempura de camaron, aguacate laminado, anguila y salsa teriyaki', prep_time_minutes: 14 },
    { name: 'Rainbow Roll', category: 'Rolls', price: 175, description: 'California roll cubierto con salmon, atun, camaron y aguacate', prep_time_minutes: 14 },
    { name: 'Volcano Roll', category: 'Rolls', price: 155, description: 'Roll empanizado relleno de cangrejo y queso crema, cubierto con mezcla spicy', prep_time_minutes: 12 },
    { name: 'Tempura Roll', category: 'Rolls', price: 140, description: 'Camaron tempura, aguacate y queso crema empanizado', prep_time_minutes: 12 },
    { name: 'Veggie Roll', category: 'Rolls', price: 95, description: 'Aguacate, pepino, zanahoria, jicama y ajonjoli', prep_time_minutes: 8 },
    { name: 'Acevichado Roll', category: 'Rolls', price: 160, description: 'Salmon y camaron en salsa acevichada con aguacate y cilantro', prep_time_minutes: 12 },
    { name: 'Dinamita Roll', category: 'Rolls', price: 150, description: 'Camaron empanizado con queso crema, jalapeno y salsa chipotle', prep_time_minutes: 12 },
    { name: 'Crunchy Roll', category: 'Rolls', price: 130, description: 'Salmon, queso crema, empanizado crunchy y salsa de anguila', prep_time_minutes: 10 },
    // Nigiri (por pieza)
    { name: 'Nigiri de Salmon', category: 'Nigiri', price: 45, description: 'Rebanada de salmon fresco sobre arroz (2 pzas)', prep_time_minutes: 4 },
    { name: 'Nigiri de Atun', category: 'Nigiri', price: 50, description: 'Rebanada de atun fresco sobre arroz (2 pzas)', prep_time_minutes: 4 },
    { name: 'Nigiri de Camaron', category: 'Nigiri', price: 45, description: 'Camaron cocido sobre arroz (2 pzas)', prep_time_minutes: 4 },
    { name: 'Nigiri de Pulpo', category: 'Nigiri', price: 55, description: 'Rebanada de pulpo sobre arroz (2 pzas)', prep_time_minutes: 4 },
    { name: 'Nigiri de Anguila', category: 'Nigiri', price: 55, description: 'Anguila glaseada con teriyaki sobre arroz (2 pzas)', prep_time_minutes: 5 },
    { name: 'Sashimi Mixto (12 pzas)', category: 'Nigiri', price: 180, description: 'Seleccion de salmon, atun, camaron y pulpo sin arroz', prep_time_minutes: 8 },
    // Entradas
    { name: 'Edamame', category: 'Entradas', price: 65, description: 'Vainas de soya al vapor con sal de mar', prep_time_minutes: 5 },
    { name: 'Gyozas (6 pzas)', category: 'Entradas', price: 85, description: 'Empanadillas japonesas de cerdo a la plancha', prep_time_minutes: 8 },
    { name: 'Takoyaki (6 pzas)', category: 'Entradas', price: 80, description: 'Bolitas de pulpo con salsa takoyaki, mayo y bonito', prep_time_minutes: 8 },
    { name: 'Tempura de Verduras', category: 'Entradas', price: 75, description: 'Verduras variadas en tempura crujiente con salsa tentsuyu', prep_time_minutes: 8 },
    { name: 'Sunomono', category: 'Entradas', price: 65, description: 'Ensalada de pepino con vinagreta de arroz y ajonjoli', prep_time_minutes: 4 },
    { name: 'Karaage (6 pzas)', category: 'Entradas', price: 90, description: 'Pollo frito japonés marinado con jengibre y soya', prep_time_minutes: 10 },
    // Sopas
    { name: 'Sopa Miso', category: 'Sopas', price: 55, description: 'Sopa de pasta de miso con tofu, alga wakame y cebolleta', prep_time_minutes: 5 },
    { name: 'Ramen Tonkotsu', category: 'Sopas', price: 135, description: 'Caldo de cerdo cremoso con noodles, huevo marinado, cerdo chashu y nori', prep_time_minutes: 12 },
    { name: 'Ramen de Pollo', category: 'Sopas', price: 120, description: 'Caldo de pollo con noodles, pollo deshebrado, maiz y nori', prep_time_minutes: 12 },
    { name: 'Udon Tempura', category: 'Sopas', price: 115, description: 'Noodles udon en caldo dashi con tempura de camaron', prep_time_minutes: 10 },
    // Bebidas
    { name: 'Te Verde', category: 'Bebidas', price: 30, description: 'Te verde japones caliente', prep_time_minutes: 3 },
    { name: 'Limonada Yuzu', category: 'Bebidas', price: 45, description: 'Limonada con citrico yuzu japones', prep_time_minutes: 3 },
    { name: 'Refresco', category: 'Bebidas', price: 30, description: 'Coca-Cola, Sprite o Fanta (355ml)', prep_time_minutes: 1 },
    { name: 'Agua Natural', category: 'Bebidas', price: 25, description: 'Agua embotellada (500ml)', prep_time_minutes: 1 },
    { name: 'Cerveza Japonesa', category: 'Bebidas', price: 65, description: 'Cerveza Asahi o Sapporo (330ml)', prep_time_minutes: 1 },
    { name: 'Sake (copa)', category: 'Bebidas', price: 75, description: 'Sake japones servido frio o tibio', prep_time_minutes: 2 },
  ],

  inventory: [
    { name: 'Arroz para Sushi', unit: 'kg', quantity: 20, low_stock_threshold: 5, category: 'Granos', cost_price: 45 },
    { name: 'Nori (hojas)', unit: 'pza', quantity: 200, low_stock_threshold: 50, category: 'Insumos', cost_price: 3 },
    { name: 'Salmon Fresco', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Pescados', cost_price: 380 },
    { name: 'Atun Fresco', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Pescados', cost_price: 420 },
    { name: 'Camaron', unit: 'kg', quantity: 6, low_stock_threshold: 2, category: 'Pescados', cost_price: 280 },
    { name: 'Pulpo', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Pescados', cost_price: 350 },
    { name: 'Anguila', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Pescados', cost_price: 450 },
    { name: 'Surimi', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Pescados', cost_price: 100 },
    { name: 'Salmon Ahumado', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Pescados', cost_price: 420 },
    { name: 'Aguacate', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Verduras', cost_price: 80 },
    { name: 'Pepino', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 20 },
    { name: 'Zanahoria', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 15 },
    { name: 'Jicama', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 18 },
    { name: 'Cebolleta', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 35 },
    { name: 'Jalapeno', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 25 },
    { name: 'Cilantro', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Verduras', cost_price: 25 },
    { name: 'Queso Crema', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Lacteos', cost_price: 90 },
    { name: 'Salsa de Soya', unit: 'lt', quantity: 5, low_stock_threshold: 1.5, category: 'Salsas', cost_price: 45 },
    { name: 'Vinagre de Arroz', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Salsas', cost_price: 50 },
    { name: 'Jengibre Encurtido', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Condimentos', cost_price: 80 },
    { name: 'Wasabi', unit: 'kg', quantity: 1, low_stock_threshold: 0.3, category: 'Condimentos', cost_price: 200 },
    { name: 'Ajonjoli', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Condimentos', cost_price: 70 },
    { name: 'Salsa Sriracha', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 60 },
    { name: 'Salsa Teriyaki', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 55 },
    { name: 'Salsa de Anguila', unit: 'lt', quantity: 1, low_stock_threshold: 0.3, category: 'Salsas', cost_price: 90 },
    { name: 'Salsa Chipotle', unit: 'lt', quantity: 1, low_stock_threshold: 0.3, category: 'Salsas', cost_price: 50 },
    { name: 'Mayonesa Japonesa', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 75 },
    { name: 'Pasta Miso', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Condimentos', cost_price: 120 },
    { name: 'Tofu', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Otros', cost_price: 40 },
    { name: 'Alga Wakame Seca', unit: 'kg', quantity: 0.5, low_stock_threshold: 0.15, category: 'Condimentos', cost_price: 250 },
    { name: 'Empanizador Panko', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Insumos', cost_price: 55 },
    { name: 'Harina Tempura', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Insumos', cost_price: 60 },
    { name: 'Edamame Congelado', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 65 },
    { name: 'Gyozas Congeladas', unit: 'pza', quantity: 60, low_stock_threshold: 15, category: 'Congelados', cost_price: 5 },
    { name: 'Mezcla Takoyaki', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Congelados', cost_price: 80 },
    { name: 'Caldo Dashi', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Salsas', cost_price: 70 },
    { name: 'Noodles Ramen', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Granos', cost_price: 50 },
    { name: 'Noodles Udon', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Granos', cost_price: 55 },
    { name: 'Cerdo Chashu', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 200 },
    { name: 'Pollo Deshebrado', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Carnes', cost_price: 110 },
    { name: 'Huevo Marinado', unit: 'pza', quantity: 20, low_stock_threshold: 5, category: 'Otros', cost_price: 6 },
    { name: 'Aceite para Freir', unit: 'lt', quantity: 8, low_stock_threshold: 2, category: 'Insumos', cost_price: 35 },
    { name: 'Sake para Cocinar', unit: 'lt', quantity: 2, low_stock_threshold: 0.5, category: 'Salsas', cost_price: 100 },
    { name: 'Bonito en Hojuelas', unit: 'kg', quantity: 0.5, low_stock_threshold: 0.15, category: 'Condimentos', cost_price: 350 },
  ],

  recipes: [
    // California Roll
    { item_name: 'California Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'California Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'California Roll', ingredient_name: 'Surimi', quantity_used: 0.06 },
    { item_name: 'California Roll', ingredient_name: 'Aguacate', quantity_used: 0.04 },
    { item_name: 'California Roll', ingredient_name: 'Pepino', quantity_used: 0.03 },
    { item_name: 'California Roll', ingredient_name: 'Ajonjoli', quantity_used: 0.005 },
    // Salmon Roll
    { item_name: 'Salmon Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Salmon Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Salmon Roll', ingredient_name: 'Salmon Fresco', quantity_used: 0.08 },
    { item_name: 'Salmon Roll', ingredient_name: 'Aguacate', quantity_used: 0.04 },
    { item_name: 'Salmon Roll', ingredient_name: 'Queso Crema', quantity_used: 0.03 },
    // Philadelphia Roll
    { item_name: 'Philadelphia Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Philadelphia Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Philadelphia Roll', ingredient_name: 'Salmon Ahumado', quantity_used: 0.07 },
    { item_name: 'Philadelphia Roll', ingredient_name: 'Queso Crema', quantity_used: 0.04 },
    { item_name: 'Philadelphia Roll', ingredient_name: 'Pepino', quantity_used: 0.03 },
    // Spicy Tuna Roll
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Atun Fresco', quantity_used: 0.08 },
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Pepino', quantity_used: 0.03 },
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Salsa Sriracha', quantity_used: 0.01 },
    { item_name: 'Spicy Tuna Roll', ingredient_name: 'Cebolleta', quantity_used: 0.01 },
    // Dragon Roll
    { item_name: 'Dragon Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Dragon Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Dragon Roll', ingredient_name: 'Camaron', quantity_used: 0.08 },
    { item_name: 'Dragon Roll', ingredient_name: 'Harina Tempura', quantity_used: 0.03 },
    { item_name: 'Dragon Roll', ingredient_name: 'Aguacate', quantity_used: 0.06 },
    { item_name: 'Dragon Roll', ingredient_name: 'Anguila', quantity_used: 0.04 },
    { item_name: 'Dragon Roll', ingredient_name: 'Salsa Teriyaki', quantity_used: 0.02 },
    // Rainbow Roll
    { item_name: 'Rainbow Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Surimi', quantity_used: 0.04 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Salmon Fresco', quantity_used: 0.04 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Atun Fresco', quantity_used: 0.04 },
    { item_name: 'Rainbow Roll', ingredient_name: 'Camaron', quantity_used: 0.04 },
    // Volcano Roll
    { item_name: 'Volcano Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Volcano Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Volcano Roll', ingredient_name: 'Surimi', quantity_used: 0.06 },
    { item_name: 'Volcano Roll', ingredient_name: 'Queso Crema', quantity_used: 0.03 },
    { item_name: 'Volcano Roll', ingredient_name: 'Empanizador Panko', quantity_used: 0.03 },
    { item_name: 'Volcano Roll', ingredient_name: 'Mayonesa Japonesa', quantity_used: 0.02 },
    { item_name: 'Volcano Roll', ingredient_name: 'Salsa Sriracha', quantity_used: 0.01 },
    // Tempura Roll
    { item_name: 'Tempura Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Tempura Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Tempura Roll', ingredient_name: 'Camaron', quantity_used: 0.08 },
    { item_name: 'Tempura Roll', ingredient_name: 'Harina Tempura', quantity_used: 0.03 },
    { item_name: 'Tempura Roll', ingredient_name: 'Aguacate', quantity_used: 0.04 },
    { item_name: 'Tempura Roll', ingredient_name: 'Queso Crema', quantity_used: 0.03 },
    { item_name: 'Tempura Roll', ingredient_name: 'Empanizador Panko', quantity_used: 0.03 },
    // Veggie Roll
    { item_name: 'Veggie Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Veggie Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Veggie Roll', ingredient_name: 'Aguacate', quantity_used: 0.04 },
    { item_name: 'Veggie Roll', ingredient_name: 'Pepino', quantity_used: 0.03 },
    { item_name: 'Veggie Roll', ingredient_name: 'Zanahoria', quantity_used: 0.02 },
    { item_name: 'Veggie Roll', ingredient_name: 'Jicama', quantity_used: 0.02 },
    { item_name: 'Veggie Roll', ingredient_name: 'Ajonjoli', quantity_used: 0.005 },
    // Acevichado Roll
    { item_name: 'Acevichado Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Acevichado Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Acevichado Roll', ingredient_name: 'Salmon Fresco', quantity_used: 0.05 },
    { item_name: 'Acevichado Roll', ingredient_name: 'Camaron', quantity_used: 0.05 },
    { item_name: 'Acevichado Roll', ingredient_name: 'Aguacate', quantity_used: 0.04 },
    { item_name: 'Acevichado Roll', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Dinamita Roll
    { item_name: 'Dinamita Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Camaron', quantity_used: 0.08 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Empanizador Panko', quantity_used: 0.03 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Queso Crema', quantity_used: 0.03 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Jalapeno', quantity_used: 0.02 },
    { item_name: 'Dinamita Roll', ingredient_name: 'Salsa Chipotle', quantity_used: 0.01 },
    // Crunchy Roll
    { item_name: 'Crunchy Roll', ingredient_name: 'Arroz para Sushi', quantity_used: 0.15 },
    { item_name: 'Crunchy Roll', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Crunchy Roll', ingredient_name: 'Salmon Fresco', quantity_used: 0.07 },
    { item_name: 'Crunchy Roll', ingredient_name: 'Queso Crema', quantity_used: 0.03 },
    { item_name: 'Crunchy Roll', ingredient_name: 'Empanizador Panko', quantity_used: 0.03 },
    { item_name: 'Crunchy Roll', ingredient_name: 'Salsa de Anguila', quantity_used: 0.02 },
    // Nigiri
    { item_name: 'Nigiri de Salmon', ingredient_name: 'Arroz para Sushi', quantity_used: 0.06 },
    { item_name: 'Nigiri de Salmon', ingredient_name: 'Salmon Fresco', quantity_used: 0.06 },
    { item_name: 'Nigiri de Atun', ingredient_name: 'Arroz para Sushi', quantity_used: 0.06 },
    { item_name: 'Nigiri de Atun', ingredient_name: 'Atun Fresco', quantity_used: 0.06 },
    { item_name: 'Nigiri de Camaron', ingredient_name: 'Arroz para Sushi', quantity_used: 0.06 },
    { item_name: 'Nigiri de Camaron', ingredient_name: 'Camaron', quantity_used: 0.06 },
    { item_name: 'Nigiri de Pulpo', ingredient_name: 'Arroz para Sushi', quantity_used: 0.06 },
    { item_name: 'Nigiri de Pulpo', ingredient_name: 'Pulpo', quantity_used: 0.06 },
    { item_name: 'Nigiri de Anguila', ingredient_name: 'Arroz para Sushi', quantity_used: 0.06 },
    { item_name: 'Nigiri de Anguila', ingredient_name: 'Anguila', quantity_used: 0.06 },
    { item_name: 'Nigiri de Anguila', ingredient_name: 'Salsa Teriyaki', quantity_used: 0.01 },
    { item_name: 'Sashimi Mixto (12 pzas)', ingredient_name: 'Salmon Fresco', quantity_used: 0.08 },
    { item_name: 'Sashimi Mixto (12 pzas)', ingredient_name: 'Atun Fresco', quantity_used: 0.08 },
    { item_name: 'Sashimi Mixto (12 pzas)', ingredient_name: 'Camaron', quantity_used: 0.06 },
    { item_name: 'Sashimi Mixto (12 pzas)', ingredient_name: 'Pulpo', quantity_used: 0.06 },
    // Entradas
    { item_name: 'Edamame', ingredient_name: 'Edamame Congelado', quantity_used: 0.15 },
    { item_name: 'Gyozas (6 pzas)', ingredient_name: 'Gyozas Congeladas', quantity_used: 6 },
    { item_name: 'Takoyaki (6 pzas)', ingredient_name: 'Mezcla Takoyaki', quantity_used: 0.10 },
    { item_name: 'Takoyaki (6 pzas)', ingredient_name: 'Pulpo', quantity_used: 0.04 },
    { item_name: 'Takoyaki (6 pzas)', ingredient_name: 'Mayonesa Japonesa', quantity_used: 0.02 },
    { item_name: 'Takoyaki (6 pzas)', ingredient_name: 'Bonito en Hojuelas', quantity_used: 0.005 },
    { item_name: 'Tempura de Verduras', ingredient_name: 'Zanahoria', quantity_used: 0.04 },
    { item_name: 'Tempura de Verduras', ingredient_name: 'Harina Tempura', quantity_used: 0.06 },
    { item_name: 'Tempura de Verduras', ingredient_name: 'Aceite para Freir', quantity_used: 0.10 },
    { item_name: 'Sunomono', ingredient_name: 'Pepino', quantity_used: 0.10 },
    { item_name: 'Sunomono', ingredient_name: 'Vinagre de Arroz', quantity_used: 0.03 },
    { item_name: 'Sunomono', ingredient_name: 'Ajonjoli', quantity_used: 0.005 },
    { item_name: 'Karaage (6 pzas)', ingredient_name: 'Pollo Deshebrado', quantity_used: 0.15 },
    { item_name: 'Karaage (6 pzas)', ingredient_name: 'Harina Tempura', quantity_used: 0.04 },
    { item_name: 'Karaage (6 pzas)', ingredient_name: 'Aceite para Freir', quantity_used: 0.08 },
    // Sopas
    { item_name: 'Sopa Miso', ingredient_name: 'Pasta Miso', quantity_used: 0.02 },
    { item_name: 'Sopa Miso', ingredient_name: 'Tofu', quantity_used: 0.04 },
    { item_name: 'Sopa Miso', ingredient_name: 'Alga Wakame Seca', quantity_used: 0.003 },
    { item_name: 'Sopa Miso', ingredient_name: 'Cebolleta', quantity_used: 0.01 },
    { item_name: 'Sopa Miso', ingredient_name: 'Caldo Dashi', quantity_used: 0.25 },
    { item_name: 'Ramen Tonkotsu', ingredient_name: 'Noodles Ramen', quantity_used: 0.15 },
    { item_name: 'Ramen Tonkotsu', ingredient_name: 'Cerdo Chashu', quantity_used: 0.08 },
    { item_name: 'Ramen Tonkotsu', ingredient_name: 'Huevo Marinado', quantity_used: 1 },
    { item_name: 'Ramen Tonkotsu', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Ramen Tonkotsu', ingredient_name: 'Cebolleta', quantity_used: 0.01 },
    { item_name: 'Ramen de Pollo', ingredient_name: 'Noodles Ramen', quantity_used: 0.15 },
    { item_name: 'Ramen de Pollo', ingredient_name: 'Pollo Deshebrado', quantity_used: 0.08 },
    { item_name: 'Ramen de Pollo', ingredient_name: 'Nori (hojas)', quantity_used: 1 },
    { item_name: 'Ramen de Pollo', ingredient_name: 'Cebolleta', quantity_used: 0.01 },
    { item_name: 'Udon Tempura', ingredient_name: 'Noodles Udon', quantity_used: 0.18 },
    { item_name: 'Udon Tempura', ingredient_name: 'Caldo Dashi', quantity_used: 0.30 },
    { item_name: 'Udon Tempura', ingredient_name: 'Camaron', quantity_used: 0.06 },
    { item_name: 'Udon Tempura', ingredient_name: 'Harina Tempura', quantity_used: 0.03 },
  ],

  modifier_groups: [
    {
      name: 'Estilo de Roll',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Tradicional', price_adjustment: 0 },
        { name: 'Empanizado', price_adjustment: 20 },
        { name: 'Tempura', price_adjustment: 25 },
      ],
      assign_to_categories: ['Rolls'],
    },
    {
      name: 'Extras',
      selection_type: 'multiple',
      required: false,
      min_selections: 0,
      max_selections: 3,
      modifiers: [
        { name: 'Aguacate Extra', price_adjustment: 20 },
        { name: 'Queso Crema Extra', price_adjustment: 15 },
        { name: 'Salmon Extra', price_adjustment: 30 },
        { name: 'Salsa Spicy', price_adjustment: 10 },
        { name: 'Ajonjoli Extra', price_adjustment: 5 },
      ],
      assign_to_categories: ['Rolls'],
    },
  ],

  combos: [
    {
      name: 'Combo Sushi',
      description: '2 rolls al gusto + sopa miso',
      combo_price: 240,
      slots: [
        { slot_label: 'Primer Roll', category: 'Rolls' },
        { slot_label: 'Segundo Roll', category: 'Rolls' },
        { slot_label: 'Sopa', category: 'Sopas' },
      ],
    },
    {
      name: 'Combo Bento',
      description: 'Roll + nigiri (2 pzas) + entrada',
      combo_price: 210,
      slots: [
        { slot_label: 'Roll', category: 'Rolls' },
        { slot_label: 'Nigiri', category: 'Nigiri' },
        { slot_label: 'Entrada', category: 'Entradas' },
      ],
    },
  ],
};
