export default {
  id: 'taqueria',
  name: 'Taqueria / Street Food',
  description: 'Tacos, quesadillas, tortas y antojitos mexicanos',
  icon: 'taco',

  categories: [
    { name: 'Tacos', sort_order: 1 },
    { name: 'Quesadillas', sort_order: 2 },
    { name: 'Tortas', sort_order: 3 },
    { name: 'Bebidas', sort_order: 4 },
    { name: 'Postres', sort_order: 5 },
  ],

  items: [
    // Tacos
    { name: 'Taco de Asada', category: 'Tacos', price: 35, description: 'Carne asada a la plancha con cebolla y cilantro', prep_time_minutes: 5 },
    { name: 'Taco al Pastor', category: 'Tacos', price: 30, description: 'Carne al pastor con piña, cebolla y cilantro', prep_time_minutes: 5 },
    { name: 'Taco de Chorizo', category: 'Tacos', price: 28, description: 'Chorizo artesanal desmenuzado', prep_time_minutes: 5 },
    { name: 'Taco de Pollo', category: 'Tacos', price: 30, description: 'Pollo a la plancha con guacamole', prep_time_minutes: 5 },
    { name: 'Taco de Suadero', category: 'Tacos', price: 32, description: 'Suadero jugoso con salsa verde', prep_time_minutes: 5 },
    { name: 'Taco de Tripa', category: 'Tacos', price: 30, description: 'Tripa dorada y crujiente', prep_time_minutes: 6 },
    { name: 'Taco de Cabeza', category: 'Tacos', price: 32, description: 'Cabeza de res deshebrada', prep_time_minutes: 4 },
    { name: 'Taco de Birria', category: 'Tacos', price: 40, description: 'Birria de res con consomé para dipping', prep_time_minutes: 6 },
    { name: 'Taco Campechano', category: 'Tacos', price: 35, description: 'Mezcla de asada, chorizo y longaniza', prep_time_minutes: 5 },
    // Quesadillas
    { name: 'Quesadilla de Queso', category: 'Quesadillas', price: 45, description: 'Queso Oaxaca fundido en tortilla grande', prep_time_minutes: 5 },
    { name: 'Quesadilla de Asada', category: 'Quesadillas', price: 60, description: 'Carne asada con queso Oaxaca', prep_time_minutes: 6 },
    { name: 'Quesadilla de Pollo', category: 'Quesadillas', price: 55, description: 'Pollo deshebrado con queso fundido', prep_time_minutes: 6 },
    { name: 'Quesadilla de Champiñones', category: 'Quesadillas', price: 50, description: 'Champiñones salteados con queso y epazote', prep_time_minutes: 6 },
    { name: 'Quesadilla de Flor de Calabaza', category: 'Quesadillas', price: 55, description: 'Flor de calabaza con queso Oaxaca', prep_time_minutes: 6 },
    // Tortas
    { name: 'Torta de Milanesa', category: 'Tortas', price: 65, description: 'Milanesa de res empanizada con aguacate, frijoles y crema', prep_time_minutes: 8 },
    { name: 'Torta de Asada', category: 'Tortas', price: 70, description: 'Carne asada con guacamole, cebolla y jalapeño', prep_time_minutes: 8 },
    { name: 'Torta de Pastor', category: 'Tortas', price: 65, description: 'Pastor con piña, queso y frijoles', prep_time_minutes: 8 },
    { name: 'Torta Cubana', category: 'Tortas', price: 75, description: 'Jamón, milanesa, salchicha, queso, aguacate y todos los ingredientes', prep_time_minutes: 10 },
    { name: 'Torta de Chorizo', category: 'Tortas', price: 60, description: 'Chorizo con queso fundido y frijoles', prep_time_minutes: 7 },
    // Bebidas
    { name: 'Agua de Horchata', category: 'Bebidas', price: 30, description: 'Agua fresca de arroz con canela y vainilla', prep_time_minutes: 1 },
    { name: 'Agua de Jamaica', category: 'Bebidas', price: 28, description: 'Agua fresca de flor de jamaica', prep_time_minutes: 1 },
    { name: 'Agua de Limón', category: 'Bebidas', price: 25, description: 'Limonada natural con hielo', prep_time_minutes: 2 },
    { name: 'Refresco', category: 'Bebidas', price: 25, description: 'Coca-Cola, Sprite o Fanta (355ml)', prep_time_minutes: 1 },
    { name: 'Cerveza', category: 'Bebidas', price: 35, description: 'Cerveza nacional (355ml)', prep_time_minutes: 1 },
    // Postres
    { name: 'Flan Napolitano', category: 'Postres', price: 35, description: 'Flan casero con caramelo', prep_time_minutes: 2 },
    { name: 'Churros (5 pzas)', category: 'Postres', price: 40, description: 'Churros crujientes con azúcar y canela', prep_time_minutes: 6 },
    { name: 'Elote en Vaso', category: 'Postres', price: 30, description: 'Granos de elote con mayonesa, queso, chile y limón', prep_time_minutes: 3 },
  ],

  inventory: [
    { name: 'Tortillas de Maíz', unit: 'kg', quantity: 30, low_stock_threshold: 8, category: 'Granos', cost_price: 22 },
    { name: 'Tortillas de Harina', unit: 'kg', quantity: 15, low_stock_threshold: 5, category: 'Granos', cost_price: 35 },
    { name: 'Carne Asada', unit: 'kg', quantity: 20, low_stock_threshold: 5, category: 'Carnes', cost_price: 220 },
    { name: 'Carne al Pastor', unit: 'kg', quantity: 20, low_stock_threshold: 5, category: 'Carnes', cost_price: 180 },
    { name: 'Chorizo', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Carnes', cost_price: 120 },
    { name: 'Pollo', unit: 'kg', quantity: 15, low_stock_threshold: 4, category: 'Carnes', cost_price: 95 },
    { name: 'Suadero', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Carnes', cost_price: 160 },
    { name: 'Tripa', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Carnes', cost_price: 90 },
    { name: 'Cabeza de Res', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Carnes', cost_price: 110 },
    { name: 'Birria de Res', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Carnes', cost_price: 200 },
    { name: 'Milanesa de Res', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Carnes', cost_price: 170 },
    { name: 'Queso Oaxaca', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Lácteos', cost_price: 130 },
    { name: 'Cebolla', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Verduras', cost_price: 18 },
    { name: 'Cilantro', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 25 },
    { name: 'Limones', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Verduras', cost_price: 30 },
    { name: 'Piña', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 20 },
    { name: 'Aguacate', unit: 'kg', quantity: 8, low_stock_threshold: 2, category: 'Verduras', cost_price: 80 },
    { name: 'Salsa Verde', unit: 'lt', quantity: 8, low_stock_threshold: 2, category: 'Salsas', cost_price: 35 },
    { name: 'Salsa Roja', unit: 'lt', quantity: 8, low_stock_threshold: 2, category: 'Salsas', cost_price: 35 },
    { name: 'Salsa Habanero', unit: 'lt', quantity: 4, low_stock_threshold: 1, category: 'Salsas', cost_price: 50 },
    { name: 'Pan Telera', unit: 'pza', quantity: 50, low_stock_threshold: 15, category: 'Pan', cost_price: 5 },
    { name: 'Frijoles Refritos', unit: 'kg', quantity: 10, low_stock_threshold: 3, category: 'Granos', cost_price: 30 },
    { name: 'Crema', unit: 'lt', quantity: 5, low_stock_threshold: 1.5, category: 'Lácteos', cost_price: 45 },
    { name: 'Champiñones', unit: 'kg', quantity: 4, low_stock_threshold: 1, category: 'Verduras', cost_price: 65 },
    { name: 'Flor de Calabaza', unit: 'kg', quantity: 3, low_stock_threshold: 1, category: 'Verduras', cost_price: 80 },
    { name: 'Jamaica Seca', unit: 'kg', quantity: 3, low_stock_threshold: 0.5, category: 'Bebidas', cost_price: 90 },
    { name: 'Base de Horchata', unit: 'kg', quantity: 5, low_stock_threshold: 1, category: 'Bebidas', cost_price: 60 },
    { name: 'Aceite Vegetal', unit: 'lt', quantity: 10, low_stock_threshold: 3, category: 'Insumos', cost_price: 35 },
    { name: 'Azúcar', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Insumos', cost_price: 25 },
    { name: 'Granos de Elote', unit: 'kg', quantity: 5, low_stock_threshold: 1.5, category: 'Verduras', cost_price: 30 },
    { name: 'Mayonesa', unit: 'lt', quantity: 3, low_stock_threshold: 1, category: 'Insumos', cost_price: 40 },
    { name: 'Chile en Polvo', unit: 'kg', quantity: 2, low_stock_threshold: 0.5, category: 'Insumos', cost_price: 60 },
  ],

  recipes: [
    // Taco de Asada
    { item_name: 'Taco de Asada', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Asada', ingredient_name: 'Carne Asada', quantity_used: 0.12 },
    { item_name: 'Taco de Asada', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Asada', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    { item_name: 'Taco de Asada', ingredient_name: 'Limones', quantity_used: 0.02 },
    // Taco al Pastor
    { item_name: 'Taco al Pastor', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco al Pastor', ingredient_name: 'Carne al Pastor', quantity_used: 0.12 },
    { item_name: 'Taco al Pastor', ingredient_name: 'Piña', quantity_used: 0.02 },
    { item_name: 'Taco al Pastor', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco al Pastor', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Taco de Chorizo
    { item_name: 'Taco de Chorizo', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Chorizo', ingredient_name: 'Chorizo', quantity_used: 0.10 },
    { item_name: 'Taco de Chorizo', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Chorizo', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Taco de Pollo
    { item_name: 'Taco de Pollo', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Pollo', ingredient_name: 'Pollo', quantity_used: 0.12 },
    { item_name: 'Taco de Pollo', ingredient_name: 'Aguacate', quantity_used: 0.03 },
    { item_name: 'Taco de Pollo', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    // Taco de Suadero
    { item_name: 'Taco de Suadero', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Suadero', ingredient_name: 'Suadero', quantity_used: 0.12 },
    { item_name: 'Taco de Suadero', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Suadero', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Taco de Tripa
    { item_name: 'Taco de Tripa', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Tripa', ingredient_name: 'Tripa', quantity_used: 0.10 },
    { item_name: 'Taco de Tripa', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Tripa', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Taco de Cabeza
    { item_name: 'Taco de Cabeza', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Cabeza', ingredient_name: 'Cabeza de Res', quantity_used: 0.12 },
    { item_name: 'Taco de Cabeza', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Cabeza', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Taco de Birria
    { item_name: 'Taco de Birria', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco de Birria', ingredient_name: 'Birria de Res', quantity_used: 0.15 },
    { item_name: 'Taco de Birria', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco de Birria', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    { item_name: 'Taco de Birria', ingredient_name: 'Limones', quantity_used: 0.02 },
    // Taco Campechano
    { item_name: 'Taco Campechano', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.06 },
    { item_name: 'Taco Campechano', ingredient_name: 'Carne Asada', quantity_used: 0.06 },
    { item_name: 'Taco Campechano', ingredient_name: 'Chorizo', quantity_used: 0.05 },
    { item_name: 'Taco Campechano', ingredient_name: 'Cebolla', quantity_used: 0.02 },
    { item_name: 'Taco Campechano', ingredient_name: 'Cilantro', quantity_used: 0.01 },
    // Quesadilla de Queso
    { item_name: 'Quesadilla de Queso', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.10 },
    { item_name: 'Quesadilla de Queso', ingredient_name: 'Queso Oaxaca', quantity_used: 0.10 },
    // Quesadilla de Asada
    { item_name: 'Quesadilla de Asada', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.10 },
    { item_name: 'Quesadilla de Asada', ingredient_name: 'Queso Oaxaca', quantity_used: 0.08 },
    { item_name: 'Quesadilla de Asada', ingredient_name: 'Carne Asada', quantity_used: 0.10 },
    // Quesadilla de Pollo
    { item_name: 'Quesadilla de Pollo', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.10 },
    { item_name: 'Quesadilla de Pollo', ingredient_name: 'Queso Oaxaca', quantity_used: 0.08 },
    { item_name: 'Quesadilla de Pollo', ingredient_name: 'Pollo', quantity_used: 0.10 },
    // Quesadilla de Champiñones
    { item_name: 'Quesadilla de Champiñones', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.10 },
    { item_name: 'Quesadilla de Champiñones', ingredient_name: 'Queso Oaxaca', quantity_used: 0.08 },
    { item_name: 'Quesadilla de Champiñones', ingredient_name: 'Champiñones', quantity_used: 0.08 },
    // Quesadilla de Flor de Calabaza
    { item_name: 'Quesadilla de Flor de Calabaza', ingredient_name: 'Tortillas de Maíz', quantity_used: 0.10 },
    { item_name: 'Quesadilla de Flor de Calabaza', ingredient_name: 'Queso Oaxaca', quantity_used: 0.08 },
    { item_name: 'Quesadilla de Flor de Calabaza', ingredient_name: 'Flor de Calabaza', quantity_used: 0.08 },
    // Torta de Milanesa
    { item_name: 'Torta de Milanesa', ingredient_name: 'Pan Telera', quantity_used: 1 },
    { item_name: 'Torta de Milanesa', ingredient_name: 'Milanesa de Res', quantity_used: 0.15 },
    { item_name: 'Torta de Milanesa', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'Torta de Milanesa', ingredient_name: 'Frijoles Refritos', quantity_used: 0.04 },
    { item_name: 'Torta de Milanesa', ingredient_name: 'Crema', quantity_used: 0.02 },
    // Torta de Asada
    { item_name: 'Torta de Asada', ingredient_name: 'Pan Telera', quantity_used: 1 },
    { item_name: 'Torta de Asada', ingredient_name: 'Carne Asada', quantity_used: 0.15 },
    { item_name: 'Torta de Asada', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'Torta de Asada', ingredient_name: 'Cebolla', quantity_used: 0.03 },
    // Torta de Pastor
    { item_name: 'Torta de Pastor', ingredient_name: 'Pan Telera', quantity_used: 1 },
    { item_name: 'Torta de Pastor', ingredient_name: 'Carne al Pastor', quantity_used: 0.15 },
    { item_name: 'Torta de Pastor', ingredient_name: 'Piña', quantity_used: 0.03 },
    { item_name: 'Torta de Pastor', ingredient_name: 'Queso Oaxaca', quantity_used: 0.05 },
    { item_name: 'Torta de Pastor', ingredient_name: 'Frijoles Refritos', quantity_used: 0.04 },
    // Torta Cubana
    { item_name: 'Torta Cubana', ingredient_name: 'Pan Telera', quantity_used: 1 },
    { item_name: 'Torta Cubana', ingredient_name: 'Milanesa de Res', quantity_used: 0.10 },
    { item_name: 'Torta Cubana', ingredient_name: 'Queso Oaxaca', quantity_used: 0.05 },
    { item_name: 'Torta Cubana', ingredient_name: 'Aguacate', quantity_used: 0.05 },
    { item_name: 'Torta Cubana', ingredient_name: 'Frijoles Refritos', quantity_used: 0.04 },
    { item_name: 'Torta Cubana', ingredient_name: 'Crema', quantity_used: 0.02 },
    // Torta de Chorizo
    { item_name: 'Torta de Chorizo', ingredient_name: 'Pan Telera', quantity_used: 1 },
    { item_name: 'Torta de Chorizo', ingredient_name: 'Chorizo', quantity_used: 0.12 },
    { item_name: 'Torta de Chorizo', ingredient_name: 'Queso Oaxaca', quantity_used: 0.06 },
    { item_name: 'Torta de Chorizo', ingredient_name: 'Frijoles Refritos', quantity_used: 0.04 },
    // Bebidas
    { item_name: 'Agua de Horchata', ingredient_name: 'Base de Horchata', quantity_used: 0.05 },
    { item_name: 'Agua de Jamaica', ingredient_name: 'Jamaica Seca', quantity_used: 0.03 },
    { item_name: 'Agua de Jamaica', ingredient_name: 'Azúcar', quantity_used: 0.04 },
    { item_name: 'Agua de Limón', ingredient_name: 'Limones', quantity_used: 0.10 },
    { item_name: 'Agua de Limón', ingredient_name: 'Azúcar', quantity_used: 0.04 },
    // Postres
    { item_name: 'Churros (5 pzas)', ingredient_name: 'Aceite Vegetal', quantity_used: 0.10 },
    { item_name: 'Churros (5 pzas)', ingredient_name: 'Azúcar', quantity_used: 0.03 },
    { item_name: 'Elote en Vaso', ingredient_name: 'Granos de Elote', quantity_used: 0.15 },
    { item_name: 'Elote en Vaso', ingredient_name: 'Mayonesa', quantity_used: 0.02 },
    { item_name: 'Elote en Vaso', ingredient_name: 'Chile en Polvo', quantity_used: 0.005 },
    { item_name: 'Elote en Vaso', ingredient_name: 'Limones', quantity_used: 0.02 },
  ],

  modifier_groups: [
    {
      name: 'Salsa',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Salsa Verde', price_adjustment: 0 },
        { name: 'Salsa Roja', price_adjustment: 0 },
        { name: 'Salsa Habanero', price_adjustment: 0 },
        { name: 'Sin Salsa', price_adjustment: 0 },
      ],
      assign_to_categories: ['Tacos', 'Quesadillas', 'Tortas'],
    },
    {
      name: 'Extras',
      selection_type: 'multiple',
      required: false,
      min_selections: 0,
      max_selections: 3,
      modifiers: [
        { name: 'Guacamole', price_adjustment: 15 },
        { name: 'Queso Extra', price_adjustment: 12 },
        { name: 'Doble Carne', price_adjustment: 25 },
        { name: 'Cebolla Asada', price_adjustment: 8 },
      ],
      assign_to_categories: ['Tacos', 'Quesadillas', 'Tortas'],
    },
    {
      name: 'Tortilla',
      selection_type: 'single',
      required: false,
      min_selections: 0,
      max_selections: 1,
      modifiers: [
        { name: 'Maíz', price_adjustment: 0 },
        { name: 'Harina', price_adjustment: 0 },
      ],
      assign_to_categories: ['Tacos', 'Quesadillas'],
    },
  ],

  combos: [
    {
      name: 'Combo Taquero',
      description: '2 tacos al gusto + bebida',
      combo_price: 75,
      slots: [
        { slot_label: 'Primer Taco', category: 'Tacos' },
        { slot_label: 'Segundo Taco', category: 'Tacos' },
        { slot_label: 'Bebida', category: 'Bebidas' },
      ],
    },
    {
      name: 'Combo Torta',
      description: 'Torta al gusto + bebida',
      combo_price: 85,
      slots: [
        { slot_label: 'Torta', category: 'Tortas' },
        { slot_label: 'Bebida', category: 'Bebidas' },
      ],
    },
  ],
};
